# Generated by Django 5.2 on 2025-05-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='账户锁定至'),
        ),
        migrations.AddField(
            model_name='user',
            name='cookie_consent',
            field=models.CharField(choices=[('none', '无同意'), ('necessary', '仅必要Cookie'), ('all', '所有Cookie')], default='necessary', max_length=20, verbose_name='Cookie同意'),
        ),
        migrations.AddField(
            model_name='user',
            name='data_processing_consent',
            field=models.BooleanField(default=True, verbose_name='数据处理同意'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='邮箱已验证'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, verbose_name='失败登录尝试'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后失败登录'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后密码修改'),
        ),
        migrations.AddField(
            model_name='user',
            name='newsletter_subscription',
            field=models.BooleanField(default=False, verbose_name='订阅通讯'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='注册IP'),
        ),
    ]
