# Generated by Django 5.2 on 2025-05-07 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='院系名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='院系代码')),
                ('description', models.TextField(blank=True, null=True, verbose_name='院系描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '院系',
                'verbose_name_plural': '院系',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='课程编号')),
                ('name', models.CharField(max_length=100, verbose_name='课程名称')),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='学分')),
                ('teacher', models.CharField(max_length=50, verbose_name='任课教师')),
                ('description', models.TextField(blank=True, null=True, verbose_name='课程描述')),
                ('class_time', models.CharField(max_length=50, verbose_name='上课时间')),
                ('location', models.CharField(max_length=50, verbose_name='上课地点')),
                ('capacity', models.PositiveIntegerField(verbose_name='课程容量')),
                ('semester', models.CharField(max_length=20, verbose_name='开课学期')),
                ('status', models.CharField(choices=[('active', '已开课'), ('pending', '待开课'), ('completed', '已结课'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='课程状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='students.department', verbose_name='所属院系')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
    ]
