# Generated by Django 5.2 on 2025-05-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$260000$default$default', help_text='学生登录密码，默认为学号', max_length=128, verbose_name='密码'),
        ),
    ]
