version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        BUILDKIT_INLINE_CACHE: 1
    restart: always
    volumes:
      - ./:/app:rw
      - uwsgi_socket:/tmp
    depends_on:
      - db
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3306
      - DJANGO_DB_NAME=studentinfo
      - DJANGO_DB_USER=root
      - DJANGO_DB_PASSWORD=password
      - DJANGO_SETTINGS_MODULE=StudentInfo.settings_docker
    command: uwsgi --ini uwsgi.ini

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - uwsgi_socket:/tmp
    depends_on:
      - web

  db:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=studentinfo
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "13306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
    driver: local
  uwsgi_socket:
    driver: local 
