# Generated by Django 5.2 on 2025-05-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentnotification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='action_url',
            field=models.URLField(blank=True, null=True, verbose_name='操作链接'),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='notifications/', verbose_name='附件'),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='priority',
            field=models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='优先级'),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='发送者'),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='type',
            field=models.CharField(choices=[('course', '课程通知'), ('exam', '考试通知'), ('grade', '成绩通知'), ('system', '系统通知'), ('academic', '学术通知')], default='system', max_length=20, verbose_name='类型'),
        ),
    ]
